-- MySQL Script generated by MySQL Workbench
-- Mon Feb  5 01:21:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema database_A
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `database_A` ;

-- -----------------------------------------------------
-- Schema database_A
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `database_A` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `database_A` ;

-- -----------------------------------------------------
-- Table `database_A`.`institutions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`institutions` ;

CREATE TABLE IF NOT EXISTS `database_A`.`institutions` (
  `ID_Institutions` INT NOT NULL,
  `Name` VARCHAR(100) NULL DEFAULT NULL,
  `Address1` VARCHAR(50) NULL DEFAULT NULL,
  `Address2` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Institutions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_A`.`lecturers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`lecturers` ;

CREATE TABLE IF NOT EXISTS `database_A`.`lecturers` (
  `ID_Lecturers` INT NOT NULL,
  `Title` VARCHAR(10) NULL DEFAULT NULL,
  `Initial_Name` VARCHAR(10) NULL DEFAULT NULL,
  `Family_Name` VARCHAR(50) NULL DEFAULT NULL,
  `ID_Institutions` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Lecturers`),
  INDEX `ID_Institutions` (`ID_Institutions` ASC) VISIBLE,
  CONSTRAINT `lecturers_ibfk_1`
    FOREIGN KEY (`ID_Institutions`)
    REFERENCES `database_A`.`institutions` (`ID_Institutions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_A`.`courses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`courses` ;

CREATE TABLE IF NOT EXISTS `database_A`.`courses` (
  `ID_Courses` INT NOT NULL,
  `Course_Code` VARCHAR(10) NULL DEFAULT NULL,
  `Course_Name` VARCHAR(100) NULL DEFAULT NULL,
  `ID_Lecturers` INT NULL DEFAULT NULL,
  `Date` DATE NULL DEFAULT NULL,
  `Place` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Courses`),
  INDEX `ID_Lecturers` (`ID_Lecturers` ASC) VISIBLE,
  CONSTRAINT `courses_ibfk_1`
    FOREIGN KEY (`ID_Lecturers`)
    REFERENCES `database_A`.`lecturers` (`ID_Lecturers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_A`.`positions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`positions` ;

CREATE TABLE IF NOT EXISTS `database_A`.`positions` (
  `ID_Positions` INT NOT NULL,
  `Position` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Positions`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_A`.`participants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`participants` ;

CREATE TABLE IF NOT EXISTS `database_A`.`participants` (
  `ID_Participants` INT NOT NULL AUTO_INCREMENT,
  `First_name` VARCHAR(50) NULL DEFAULT NULL,
  `Last_name` VARCHAR(50) NULL DEFAULT NULL,
  `ID_Positions` INT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Participants`),
  INDEX `Positionn_idx` (`ID_Positions` ASC) VISIBLE,
  CONSTRAINT `Positionn`
    FOREIGN KEY (`ID_Positions`)
    REFERENCES `database_A`.`positions` (`ID_Positions`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `database_A`.`course_grading`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `database_A`.`course_grading` ;

CREATE TABLE IF NOT EXISTS `database_A`.`course_grading` (
  `ID_Courses` INT NOT NULL,
  `ID_Participants` INT NOT NULL,
  `Grade` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ID_Courses`, `ID_Participants`),
  INDEX `course_grading_ibfk_2` (`ID_Participants` ASC) VISIBLE,
  CONSTRAINT `course_grading_ibfk_1`
    FOREIGN KEY (`ID_Courses`)
    REFERENCES `database_A`.`courses` (`ID_Courses`),
  CONSTRAINT `course_grading_ibfk_2`
    FOREIGN KEY (`ID_Participants`)
    REFERENCES `database_A`.`participants` (`ID_Participants`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
